image: Visual Studio 2017

branches:
 only:
  - hw4

before_build:
  - nuget restore F#/Homework4/Homework4/Homework4.sln

build:
  project: F#/Homework4/Homework4/Homework4.sln

test_script:
  - dotnet test F#/Homework4/Homework4/Homework4.sln

