image: Visual Studio 2017

branches:
 only:
  - hw7

before_build:
  - nuget restore F#/Homework7/Homework7.sln

build:
  project: F#/Homework7/Homework7.sln

test_script:
  - dotnet test F#/Homework7/Homework7.sln 

