image: Visual Studio 2017

branches:
 only:
  - homework6

before_build:
  - nuget restore F#/Homework6/Homework6.sln

build:
  project: F#/Homework6/Homework6.sln

test_script:
  - dotnet test F#/Homework6/Homework6.sln 