image: Visual Studio 2017

branches:
 only:
  - Homework3

before_build:
  - nuget restore Homework3/SimpleFtpClient/SimpleFtpClient.sln

build:
  project: Homework3/SimpleFtpClient/SimpleFtpClient.sln
