image: Visual Studio 2017

branches:
 only:
  - hw8

before_build:
  - nuget restore F#/Homework8/Homework8.sln

build:
  project: F#/Homework8/Homework8.sln

test_script:
  - dotnet test F#/Homework8/Homework8.sln 

