image: Visual Studio 2017

branches:
 only:
  - hw2

before_build:
  - nuget restore F#/Homework2/Homework2.sln

build:
  project: F#/Homework2/Homework2.sln

test_script:
  - dotnet test F#/Homework2/Homework2.sln 

