image: Visual Studio 2017

branches:
 only:
  - home5

before_build:
  - nuget restore F#/Homework5/Homework5.sln

build:
  project: F#/Homework5/Homework5.sln

test_script:
  - dotnet test F#/Homework5/Homework5.sln 
